# Generated by Django 3.1.6 on 2021-02-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.FloatField()),
                ('total_expense', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
    ]
