# Generated by Django 3.1.6 on 2021-02-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
