# Generated by Django 3.1.5 on 2021-01-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210122_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='mode',
            new_name='mode_of_payment',
        ),
    ]
