# Generated by Django 3.1.6 on 2021-02-06 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20210131_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expense', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
