# Generated by Django 3.1.6 on 2021-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Income', models.FloatField()),
                ('Total_Expenses', models.FloatField()),
                ('Balance', models.FloatField()),
            ],
        ),
    ]
