# Generated by Django 3.1.5 on 2021-01-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20210131_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='source',
            new_name='source_of_income',
        ),
    ]
