# Generated by Django 3.1.5 on 2021-01-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_auto_20210131_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='drop',
        ),
        migrations.DeleteModel(
            name='Dropdown',
        ),
    ]
