# Generated by Django 3.1.5 on 2021-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20210131_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='received_source',
            field=models.CharField(choices=[('select', 'select'), ('Neft Transfer', 'Neft Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], default='select', max_length=20),
        ),
    ]
