# Generated by Django 3.1.6 on 2021-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_auto_20210202_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='received_source',
            field=models.CharField(choices=[('select', 'select'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], default='select', max_length=20),
        ),
    ]
