# Generated by Django 3.1.6 on 2021-02-06 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_auto_20210203_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='income',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='received_source',
            field=models.CharField(max_length=266),
        ),
    ]
