# Generated by Django 3.1.6 on 2021-02-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_auto_20210206_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalIncome',
        ),
    ]
